spring.application.name=demo

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=demo
spring.datasource.password=demo

# JPA
spring.jpa.hibernate.ddl-auto=update

# Security
security.jwt.secret=RkY3Q2NwQXJxVXpKaHB5N2hNVzFWTnQ2YlN6QnRzQ2Y=
security.jwt.expiration-ms=3600000

# Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.cache.usd-brl-ttl-minutes=5

# Integrations
app.integrations.dollar.awesome-url=https://economia.awesomeapi.com.br/json/last/USD-BRL
app.integrations.dollar.frankfurter-url=https://api.frankfurter.app/latest?from=USD&to=BRL
