spring.application.name=demo

# Datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demo}
spring.datasource.username=${DB_USER:demo}
spring.datasource.password=${DB_PASSWORD:demo}

# JPA
spring.jpa.hibernate.ddl-auto=update

# Security
security.jwt.secret=${JWT_SECRET:RkY3Q2NwQXJxVXpKaHB5N2hNVzFWTnQ2YlN6QnRzQ2Y=}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Cache
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
app.cache.usd-brl-ttl-minutes=${USD_BRL_CACHE_TTL_MINUTES:5}

# Integrations
app.integrations.dollar.awesome-url=https://economia.awesomeapi.com.br/json/last/USD-BRL
app.integrations.dollar.frankfurter-url=https://api.frankfurter.app/latest?from=USD&to=BRL
