spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=demo
spring.datasource.password=demo

spring.jpa.hibernate.ddl-auto=update

security.jwt.secret=RkY3Q2NwQXJxVXpKaHB5N2hNVzFWTnQ2YlN6QnRzQ2Y=
security.jwt.expiration-ms=3600000
